# Generated by Django 6.0.5 on 2026-05-29 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nama Alat')),
                ('category', models.CharField(choices=[('Tenda', 'Tenda'), ('Carrier', 'Carrier'), ('Sleeping Bag', 'Sleeping Bag'), ('Matras', 'Matras'), ('Kompor', 'Kompor'), ('Perlengkapan Lain', 'Perlengkapan Lain')], max_length=100, verbose_name='Kategori')),
                ('price_per_day', models.IntegerField(verbose_name='Harga Sewa/Hari')),
                ('stock', models.IntegerField(default=0, verbose_name='Stok')),
                ('description', models.TextField(blank=True, verbose_name='Deskripsi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='equipments/', verbose_name='Gambar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Alat Camping',
                'verbose_name_plural': 'Alat Camping',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Nama Penyewa')),
                ('phone', models.CharField(max_length=20, verbose_name='No. Telepon')),
                ('start_date', models.DateField(verbose_name='Tanggal Pinjam')),
                ('end_date', models.DateField(verbose_name='Tanggal Kembali')),
                ('note', models.TextField(blank=True, verbose_name='Catatan')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Dipinjam', 'Dipinjam'), ('Selesai', 'Selesai')], default='Pending', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='rental.equipment', verbose_name='Alat')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Booking',
                'ordering': ['-created_at'],
            },
        ),
    ]
